language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - php artisan key:generate
  - php artisan migrate
  